spring.application.name=SentimentAnalysis

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/egaming
spring.datasource.username=egaming
spring.datasource.password=egaming

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=egaming
spring.rabbitmq.password=egaming
spring.rabbitmq.publisher-confirm-type=correlated

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5:1.5b
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.retry.max-attempts=1

spring.jackson.default-property-inclusion=non_null

spring.web.locale=en
spring.web.locale-resolver=fixed

management.endpoints.web.exposure.include=health,info
